# Loads environment variables from the specified files
# loadEnv:
#   files: '.env'

# This provides the HTTP REST interface for all exported resources
rest: true

# Include HTTP request logging
http:
  logging:
    timing: true
    id: true
    level: info
    path: ~/hdb/log/http.log

# These reads GraphQL schemas to define the schema of database/tables/attributes
graphqlSchema:
  files: ./data/schema.graphql

# Loads JavaScript modules such that their exports are exported as resources
jsResource:
  files: ./dist/resources/index.js
